spring:
  application:
    name: spring-aws-kinesis-producer
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  profiles:
    active: local
  cloud:
    function:
      definition: produceConsistently;produceReactive
    stream:
      bindings:
        poller:
          fixed-delay: 3000
        # NOTE: {producer bean name}-out-{sequence number}
        produceConsistently-out-0:
          destination: mtaji-test-stream
          content-type: text/plain
        produceReactive-out-0:
          destination: greeting
          content-type: application/json

server:
  port: 18080

management:
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always
  server:
    port: 38080

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
      instance-profile: false
    region:
      static: ap-northeast-1
    end-point:
      # NOTE: should blank in production env
      uri:
    stack:
      auto: false
    instance:
      data:
        enabled: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
        internal:
          InstanceMetadataServiceResourceFetcher: ERROR
